import type { WeaponDefinition, ItemDefinition } from "./types";
// Specs: Arsenal Canon v1 pp4–15. Combat numbers are tunable, not historical assertions.
export const WEAPONS: Record<string, WeaponDefinition> = Object.fromEntries(
  (
    [
      {
        id: "bb",
        name: "Vault 13 BB Gun",
        family: "bb",
        caliber: "BB",
        capacity: 10,
        damage: 2,
        penetration: 0,
        owner: null,
        region: "ironclad",
        feed: "tube",
        operation: "spring piston",
        range: "close",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: true,
        unique: true,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 1,
        art: "./art/items/bb-gun.jpg",
        authority: [],
        upgrades: [
          {
            name: "Locker Find",
            requirement: "opening",
            effect: "Pests and exposed mechanisms; never armor penetration",
            visual: "worn stock",
          },
          {
            name: "Travis Tune",
            requirement: "travis-met",
            effect: "Reliable spring seal and tube follower",
            visual: "straight barrel and brass seal",
          },
          {
            name: "Relay Peep",
            requirement: "relay-favor",
            effect: "Precision shots at exposed sensors",
            visual: "radio peep sight",
          },
          {
            name: "Porch Quiet",
            requirement: "quiet-favor",
            effect: "Harder-to-locate distraction shots",
            visual: "wrapped stock",
          },
          {
            name: "Small Things Matter",
            requirement: "tyrone-trust",
            effect: "Mark weak components, not AEGIS penetration",
            visual: "carefully restored receiver",
          },
        ],
      },
      {
        id: "service-pistol",
        name: "Service Pistol",
        family: "pistol",
        caliber: "9mm",
        capacity: 12,
        damage: 5,
        penetration: 0,
        owner: null,
        region: "ironclad",
        feed: "magazine",
        operation: "manually fired",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 1,
        art: "./art/items/pistol-service.jpg",
        authority: [],
        upgrades: [],
      },
      {
        id: "heavy-pistol",
        name: "Heavy Pistol",
        family: "pistol",
        caliber: ".45 ACP",
        capacity: 8,
        damage: 6,
        penetration: 0,
        owner: null,
        region: "ironclad",
        feed: "magazine",
        operation: "manually fired",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 1,
        art: null,
        authority: [],
        upgrades: [],
      },
      {
        id: "gate-six",
        name: "Gate Six Revolver",
        family: "revolver",
        caliber: ".357",
        capacity: 6,
        damage: 7,
        penetration: 0,
        owner: null,
        region: "ironclad",
        feed: "cylinder",
        operation: "manually fired",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: null,
        authority: [],
        upgrades: [],
      },
      {
        id: "machine-pistol",
        name: "Machine Pistol",
        family: "compact",
        caliber: "9mm",
        capacity: 20,
        damage: 6,
        penetration: 0,
        owner: null,
        region: "ironclad",
        feed: "magazine",
        operation: "manually fired",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: null,
        authority: [],
        upgrades: [],
      },
      {
        id: "subgun",
        name: "Subgun",
        family: "compact",
        caliber: ".45 ACP",
        capacity: 25,
        damage: 7,
        penetration: 0,
        owner: null,
        region: "ironclad",
        feed: "magazine",
        operation: "manually fired",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: null,
        authority: [],
        upgrades: [],
      },
      {
        id: "m4",
        name: "M4 Carbine",
        family: "carbine",
        caliber: "5.56",
        capacity: 30,
        damage: 7,
        penetration: 0,
        owner: null,
        region: "ironclad",
        feed: "magazine",
        operation: "manually fired",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: "./art/items/m4.jpg",
        authority: [],
        upgrades: [],
      },
      {
        id: "m16",
        name: "M16 Service Rifle",
        family: "carbine",
        caliber: "5.56",
        capacity: 30,
        damage: 8,
        penetration: 0,
        owner: null,
        region: "ironclad",
        feed: "magazine",
        operation: "manually fired",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: "./art/items/m16.jpg",
        authority: [],
        upgrades: [],
      },
      {
        id: "m94",
        name: "M94 Lever",
        family: "lever",
        caliber: ".30-30",
        capacity: 6,
        damage: 8,
        penetration: 0,
        owner: null,
        region: "ironclad",
        feed: "tube",
        operation: "manual lever action",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: "./art/items/lever-3030.jpg",
        authority: [],
        upgrades: [
          {
            name: "Workshop Return",
            requirement: "travis-met",
            effect: "Damaged locally repairable lever gun",
            visual: "rusted action",
          },
          {
            name: "Action Restoration",
            requirement: "spring-steel",
            effect: "Restore reliable cycling",
            visual: "clean receiver",
          },
          {
            name: "Rail Peep",
            requirement: "optical-glass",
            effect: "Aimed shots expose joints and interrupt heavy fire",
            visual: "brass peep and barrel band",
          },
        ],
      },
      {
        id: "m336",
        name: "M336 Brush Gun",
        family: "lever",
        caliber: ".30-30",
        capacity: 6,
        damage: 8,
        penetration: 0,
        owner: null,
        region: "ironclad",
        feed: "tube",
        operation: "manual lever action",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: "./art/items/lever-3030.jpg",
        authority: [],
        upgrades: [],
      },
      {
        id: "m700",
        name: "M700 Survey",
        family: "hunting",
        caliber: ".270",
        capacity: 5,
        damage: 9,
        penetration: 0,
        owner: null,
        region: "ironclad",
        feed: "magazine",
        operation: "manually fired",
        range: "long",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: "./art/items/m700.jpg",
        authority: [],
        upgrades: [],
      },
      {
        id: "m70",
        name: "M70 Springfield",
        family: "hunting",
        caliber: ".30-06",
        capacity: 5,
        damage: 10,
        penetration: 0,
        owner: null,
        region: "ironclad",
        feed: "magazine",
        operation: "manually fired",
        range: "long",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: "./art/items/m70.jpg",
        authority: [],
        upgrades: [],
      },
      {
        id: "m14",
        name: "M14 Battle Rifle",
        family: "marksman",
        caliber: ".308",
        capacity: 20,
        damage: 9,
        penetration: 1,
        owner: null,
        region: "ironclad",
        feed: "magazine",
        operation: "manually fired",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 3,
        art: "./art/items/m14.jpg",
        authority: [],
        upgrades: [],
      },
      {
        id: "m10",
        name: "M10 Battle Rifle",
        family: "marksman",
        caliber: ".308",
        capacity: 20,
        damage: 9,
        penetration: 1,
        owner: null,
        region: "veyra",
        feed: "magazine",
        operation: "manually fired",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 3,
        art: null,
        authority: [],
        upgrades: [],
      },
      {
        id: "m24",
        name: "M24 Marksman",
        family: "marksman",
        caliber: ".308",
        capacity: 5,
        damage: 10,
        penetration: 1,
        owner: null,
        region: "ironclad",
        feed: "magazine",
        operation: "manually fired",
        range: "long",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 3,
        art: null,
        authority: [],
        upgrades: [],
      },
      {
        id: "m70-magnum",
        name: "M70 Magnum",
        family: "marksman",
        caliber: ".300 Win Mag",
        capacity: 4,
        damage: 11,
        penetration: 2,
        owner: null,
        region: "ironclad",
        feed: "magazine",
        operation: "manually fired",
        range: "long",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 3,
        art: "./art/items/m70.jpg",
        authority: [],
        upgrades: [],
      },
      {
        id: "pump",
        name: "Pump Shotgun",
        family: "shotgun",
        caliber: "12g",
        capacity: 5,
        damage: 10,
        penetration: 0,
        owner: null,
        region: "ironclad",
        feed: "tube",
        operation: "manually fired",
        range: "close",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: "./art/items/shotgun-pump.jpg",
        authority: [],
        upgrades: [],
      },
      {
        id: "combat-shotgun",
        name: "Combat Shotgun",
        family: "shotgun",
        caliber: "12g",
        capacity: 6,
        damage: 10,
        penetration: 0,
        owner: null,
        region: "ironclad",
        feed: "magazine",
        operation: "manually fired",
        range: "close",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: null,
        authority: [],
        upgrades: [],
      },
      {
        id: "pack-tooth",
        name: "Pack-Tooth Scattergun",
        family: "shotgun",
        caliber: "12g",
        capacity: 6,
        damage: 10,
        penetration: 0,
        owner: null,
        region: "ironclad",
        feed: "magazine",
        operation: "manually fired",
        range: "close",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: null,
        authority: [],
        upgrades: [],
      },
      {
        id: "cinder-bess",
        name: "Cinder Bess Scatter",
        family: "shotgun",
        caliber: "12g",
        capacity: 5,
        damage: 10,
        penetration: 0,
        owner: null,
        region: "slagtown",
        feed: "magazine",
        operation: "manually fired",
        range: "close",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: null,
        authority: [],
        upgrades: [],
      },
      {
        id: "saw",
        name: "SAW",
        family: "support",
        caliber: "5.56",
        capacity: 60,
        damage: 10,
        penetration: 0,
        owner: null,
        region: "ironclad",
        feed: "belt",
        operation: "manually fired",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 3,
        art: "./art/items/saw.jpg",
        authority: [],
        upgrades: [],
      },
      {
        id: "salt-wren",
        name: "Salt-Wren Harpoon",
        family: "heavy",
        caliber: "harpoon bolt",
        capacity: 1,
        damage: 10,
        penetration: 0,
        owner: null,
        region: "brasswater",
        feed: "manual",
        operation: "manually fired",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 3,
        art: "./art/items/harpoon.jpg",
        authority: [],
        upgrades: [],
      },
      {
        id: "l4",
        name: "L4 Pulse",
        family: "energy",
        caliber: "laser capacitor",
        capacity: 6,
        damage: 8,
        penetration: 2,
        owner: null,
        region: "veyra",
        feed: "cell",
        operation: "manually fired",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: null,
        authority: [],
        upgrades: [],
      },
      {
        id: "l6",
        name: "L6 Carbine",
        family: "energy",
        caliber: "laser capacitor",
        capacity: 6,
        damage: 10,
        penetration: 2,
        owner: null,
        region: "veyra",
        feed: "cell",
        operation: "manually fired",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: null,
        authority: [],
        upgrades: [],
      },
      {
        id: "l8",
        name: "L8 Coherent Rifle",
        family: "energy",
        caliber: "laser capacitor",
        capacity: 6,
        damage: 12,
        penetration: 2,
        owner: null,
        region: "veyra",
        feed: "cell",
        operation: "manually fired",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: null,
        authority: [],
        upgrades: [],
      },
      {
        id: "last-receipt",
        name: "Last Receipt",
        family: "lever",
        caliber: ".45-70",
        capacity: 1,
        damage: 14,
        penetration: 3,
        owner: "travis",
        region: "ironclad",
        feed: "manual",
        operation: "manually operated lever action",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Legendary",
        named: true,
        unique: true,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: null,
        authority: [],
        upgrades: [
          {
            name: "Bay Rifle",
            requirement: "travis",
            effect: "Manual .45-70, scarce ammunition",
            visual: "shroud and brass loops",
          },
          {
            name: "Handload Book",
            requirement: "travis-jobs",
            effect: "Ball, bonded hunting and heavy penetrator recipes",
            visual: "handload brass loops",
          },
          {
            name: "Blackglass Peep",
            requirement: "blackspire-alliance",
            effect: "Readable non-networked sight in snow, smoke and EMP",
            visual: "luminous peep insert",
          },
          {
            name: "Breaker Sleeve",
            requirement: "aegis-material",
            effect: "Chamber reinforcement for anti-plate loads",
            visual: "ceramic sleeve and reinforced stock",
          },
          {
            name: "Receipt Paid",
            requirement: "travis-secured",
            effect:
              "First deliberate discovered-joint shot can break a powered component",
            visual: "Bay 13 maker plate",
          },
        ],
      },
      {
        id: "ridge-glass",
        name: "Ridge Glass",
        family: "marksman",
        caliber: ".338 Lapua",
        capacity: 4,
        damage: 13,
        penetration: 3,
        owner: "lyra",
        region: "ironclad",
        feed: "magazine",
        operation: "manually fired",
        range: "long",
        accuracy: 75,
        recoil: 2,
        rarity: "Legendary",
        named: true,
        unique: true,
        faction: "aegis",
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 3,
        art: "./art/items/ridge-glass.jpg",
        authority: [],
        upgrades: [
          {
            name: "LYRA-4 issue",
            requirement: "lyra",
            effect: "AP3 suppressed .338 Lapua, four rounds",
            visual: "suppressor",
          },
          {
            name: "Pale Glass Zero",
            requirement: "lyra-recovery",
            effect: "Optic stability restored",
            visual: "calibrated optic",
          },
          {
            name: "MOTH Link",
            requirement: "moth-intact",
            effect: "Observation and movement history",
            visual: "microdrone link",
          },
          {
            name: "Witness Optic",
            requirement: "lyra-blackbox",
            effect: "Authenticated observations become evidence",
            visual: "recording optic",
          },
          {
            name: "White Mark",
            requirement: "lyra-allied",
            effect: "Prepared fire needs Lyra alive and allied",
            visual: "white sight housing",
          },
        ],
      },
      {
        id: "manifest",
        name: "Manifest",
        family: "carbine",
        caliber: "6.8x51",
        capacity: 30,
        damage: 10,
        penetration: 1,
        owner: "vera",
        region: "slagtown",
        feed: "magazine",
        operation: "select-fire",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Legendary",
        named: true,
        unique: true,
        faction: "aegis",
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: "./art/items/manifest-rifle.jpg",
        authority: [],
        upgrades: [
          {
            name: "Manifest",
            requirement: "vera",
            effect: "6.8x51, thirty rounds, select-fire",
            visual: "mechanical counter",
          },
          {
            name: "Audit Counter",
            requirement: "counter-intact",
            effect: "Actual rounds expose falsified seizure logs",
            visual: "restored counter",
          },
          {
            name: "Warrant Handshake",
            requirement: "warrant-valid",
            effect: "Compatible doors require Spike and credentials",
            visual: "physical handshake port",
          },
          {
            name: "Edict Sync",
            requirement: "vera-allied",
            effect: "Controlled lanes and civilian protection",
            visual: "projector interface",
          },
          {
            name: "Law or Order",
            requirement: "vera-defected",
            effect: "Charter evidence if Vera defects; loot is not authority",
            visual: "charter seal",
          },
        ],
      },
      {
        id: "bulkhead-twelve",
        name: "Bulkhead Twelve",
        family: "shotgun",
        caliber: "12g 3-inch magnum",
        capacity: 5,
        damage: 14,
        penetration: 0,
        owner: "drake",
        region: "slagtown",
        feed: "magazine",
        operation: "manually fired",
        range: "close",
        accuracy: 75,
        recoil: 2,
        rarity: "Legendary",
        named: true,
        unique: true,
        faction: "aegis",
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: "./art/items/bulkhead-twelve.jpg",
        authority: [],
        upgrades: [
          {
            name: "Bulkhead Twelve",
            requirement: "drake",
            effect: "Five-round 3-inch magnum box",
            visual: "box magazine",
          },
          {
            name: "Breach Choke",
            requirement: "breach-parts",
            effect: "Hinge and lock pattern, not sniping",
            visual: "breach choke",
          },
          {
            name: "Inertial Stock",
            requirement: "inertial-parts",
            effect: "Recoil control during armored movement",
            visual: "buffered stock",
          },
          {
            name: "Door Tax",
            requirement: "door-tax",
            effect: "Microcharges change breach geometry",
            visual: "charge carrier",
          },
          {
            name: "Second Knock Sync",
            requirement: "drake-allied",
            effect: "Non-firefight breach routes need his knowledge",
            visual: "maul link",
          },
        ],
      },
      {
        id: "halo-lance",
        name: "Halo Lance",
        family: "energy",
        caliber: "violet plasma cell",
        capacity: 6,
        damage: 14,
        penetration: 2,
        owner: "orion",
        region: "veyra",
        feed: "cell",
        operation: "six-shot violet plasma",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Legendary",
        named: true,
        unique: true,
        faction: "aegis",
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: "./art/items/halo-lance.jpg",
        authority: [],
        upgrades: [
          {
            name: "Halo Lance",
            requirement: "orion",
            effect: "Six-shot violet plasma; legacy 2d8 AP2",
            visual: "violet chamber",
          },
          {
            name: "Violet Regulator",
            requirement: "mercer-expertise",
            effect: "Stable heat and shot consistency",
            visual: "regulator",
          },
          {
            name: "Crown Link",
            requirement: "crown-authorized",
            effect: "Punish repeated behavior",
            visual: "prediction interface",
          },
          {
            name: "Grav-Hook Rhythm",
            requirement: "orion-training",
            effect: "Combine movement and weapon kit",
            visual: "hook interface",
          },
          {
            name: "Open the Room",
            requirement: "orion-allied",
            effect: "Orion expertise cannot be inherited by killing him",
            visual: "violet link",
          },
        ],
      },
      {
        id: "hounds-tooth",
        name: "Hound\u2019s Tooth",
        family: "heavy",
        caliber: ".50 anti-material",
        capacity: 1,
        damage: 16,
        penetration: 4,
        owner: "gravenor",
        region: "ironclad",
        feed: "manual",
        operation: "manually fired",
        range: "long",
        accuracy: 75,
        recoil: 2,
        rarity: "Legendary",
        named: true,
        unique: true,
        faction: "ashen",
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 3,
        art: null,
        authority: [],
        upgrades: [
          {
            name: "Convoy Rifle",
            requirement: "gravenor",
            effect: "Loud slow .50 anti-material",
            visual: "field wrap",
          },
          {
            name: "Pack Bipod",
            requirement: "pack-parts",
            effect: "Prepared mountain fire",
            visual: "mountain bipod",
          },
          {
            name: "Route Glass",
            requirement: "ashen-routes",
            effect: "Etched local range references",
            visual: "etched optic",
          },
          {
            name: "Ceramic Breaker",
            requirement: "vesper-penetrators",
            effect: "AEGIS joint and vehicle recipe",
            visual: "reinforced chamber",
          },
          {
            name: "Roadbreaker",
            requirement: "gravenor-allied",
            effect: "Honorable acquisition gives scout marking network",
            visual: "Pack marks",
          },
        ],
      },
      {
        id: "true-north",
        name: "True North",
        family: "survey",
        caliber: "survey charge",
        capacity: 1,
        damage: 10,
        penetration: 2,
        owner: "thessaly",
        region: "blackspire",
        feed: "manual",
        operation: "magnetic-resonance survey",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Legendary",
        named: true,
        unique: true,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: null,
        authority: [],
        upgrades: [
          {
            name: "Survey Rifle",
            requirement: "thessaly",
            effect: "Magnetic resonance survey charges",
            visual: "ranging body",
          },
          {
            name: "Scar Calibration",
            requirement: "scar-data",
            effect: "Read density and unstable structures",
            visual: "calibration rails",
          },
          {
            name: "Seismic Tag Link",
            requirement: "seismic-tags",
            effect: "Route warnings and demolition data",
            visual: "tag receiver",
          },
          {
            name: "Blackglass Lens",
            requirement: "blackglass",
            effect: "Non-networked material discrimination",
            visual: "blackglass optic",
          },
          {
            name: "The Map Tells the Truth",
            requirement: "thessaly-allied",
            effect: "Compare falsified data with terrain",
            visual: "map overlay lens",
          },
        ],
      },
      {
        id: "clause",
        name: "Clause",
        family: "pistol",
        caliber: "10mm",
        capacity: 10,
        damage: 8,
        penetration: 1,
        owner: "kane",
        region: "veyra",
        feed: "magazine",
        operation: "magnetic-assisted",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Legendary",
        named: true,
        unique: true,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 1,
        art: null,
        authority: [],
        upgrades: [],
      },
      {
        id: "redaction",
        name: "Redaction",
        family: "compact",
        caliber: "5.7mm",
        capacity: 20,
        damage: 8,
        penetration: 1,
        owner: "reeve",
        region: "veyra",
        feed: "magazine",
        operation: "suppressed PDW",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Legendary",
        named: true,
        unique: true,
        faction: null,
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 2,
        art: null,
        authority: [],
        upgrades: [],
      },
      {
        id: "pale-horse",
        name: "Pale Horse",
        family: "marksman",
        caliber: "8.6 coil-assisted",
        capacity: 8,
        damage: 13,
        penetration: 3,
        owner: "vale",
        region: "veyra",
        feed: "magazine",
        operation: "manually fired",
        range: "mid",
        accuracy: 75,
        recoil: 2,
        rarity: "Legendary",
        named: true,
        unique: true,
        faction: "aegis",
        slots: ["optic", "muzzle", "barrel", "feed", "stock", "receiver"],
        load: 3,
        art: null,
        authority: [],
        upgrades: [],
      },
      {
        id: "work-knife",
        name: "Vault 13 Work Knife",
        family: "knife",
        caliber: null,
        capacity: 0,
        damage: 4,
        penetration: 0,
        owner: null,
        region: "ironclad",
        feed: "none",
        operation: "manually fired",
        range: "close",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: [],
        load: 1,
        art: null,
        authority: [],
        upgrades: [],
      },
      {
        id: "route-throwers",
        name: "Route Throwers",
        family: "knife",
        caliber: null,
        capacity: 0,
        damage: 4,
        penetration: 0,
        owner: null,
        region: "ironclad",
        feed: "none",
        operation: "manually fired",
        range: "close",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: [],
        load: 1,
        art: null,
        authority: [],
        upgrades: [],
      },
      {
        id: "furnace-cleaver",
        name: "Furnace Cleaver",
        family: "knife",
        caliber: null,
        capacity: 0,
        damage: 4,
        penetration: 0,
        owner: null,
        region: "slagtown",
        feed: "none",
        operation: "manually fired",
        range: "close",
        accuracy: 75,
        recoil: 2,
        rarity: "Common",
        named: false,
        unique: false,
        faction: null,
        slots: [],
        load: 1,
        art: null,
        authority: [],
        upgrades: [],
      },
      {
        id: "mast-knife",
        name: "Mast Knife",
        family: "knife",
        caliber: null,
        capacity: 0,
        damage: 4,
        penetration: 0,
        owner: "lyra",
        region: "ironclad",
        feed: "none",
        operation: "manually fired",
        range: "close",
        accuracy: 75,
        recoil: 2,
        rarity: "Legendary",
        named: true,
        unique: true,
        faction: "aegis",
        slots: [],
        load: 1,
        art: "./art/items/mast-knife.jpg",
        authority: [],
        upgrades: [],
      },
      {
        id: "warrant-spike",
        name: "Warrant Spike",
        family: "knife",
        caliber: null,
        capacity: 0,
        damage: 4,
        penetration: 0,
        owner: "vera",
        region: "slagtown",
        feed: "none",
        operation: "manually fired",
        range: "close",
        accuracy: 75,
        recoil: 2,
        rarity: "Legendary",
        named: true,
        unique: true,
        faction: "aegis",
        slots: [],
        load: 1,
        art: "./art/items/warrant-spike.jpg",
        authority: ["vesper-container"],
        upgrades: [],
      },
      {
        id: "second-knock",
        name: "Second Knock",
        family: "maul",
        caliber: null,
        capacity: 0,
        damage: 10,
        penetration: 0,
        owner: "drake",
        region: "slagtown",
        feed: "none",
        operation: "manually fired",
        range: "close",
        accuracy: 75,
        recoil: 2,
        rarity: "Legendary",
        named: true,
        unique: true,
        faction: "aegis",
        slots: [],
        load: 2,
        art: "./art/items/second-knock.jpg",
        authority: [],
        upgrades: [],
      },
      {
        id: "sevens-cestus",
        name: "Seven\u2019s Cestus",
        family: "gauntlet",
        caliber: null,
        capacity: 0,
        damage: 10,
        penetration: 0,
        owner: "orion",
        region: "veyra",
        feed: "none",
        operation: "manually fired",
        range: "close",
        accuracy: 75,
        recoil: 2,
        rarity: "Legendary",
        named: true,
        unique: true,
        faction: "aegis",
        slots: [],
        load: 2,
        art: "./art/items/sevens-cestus.jpg",
        authority: [],
        upgrades: [],
      },
      {
        id: "command-pike",
        name: "Command Pike",
        family: "polearm",
        caliber: null,
        capacity: 0,
        damage: 10,
        penetration: 0,
        owner: "vale",
        region: "veyra",
        feed: "none",
        operation: "manually fired",
        range: "close",
        accuracy: 75,
        recoil: 2,
        rarity: "Legendary",
        named: true,
        unique: true,
        faction: "aegis",
        slots: [],
        load: 2,
        art: null,
        authority: [],
        upgrades: [],
      },
      {
        id: "gate-spear",
        name: "Gate Spear",
        family: "polearm",
        caliber: null,
        capacity: 0,
        damage: 10,
        penetration: 0,
        owner: "warden",
        region: "veyra",
        feed: "none",
        operation: "manually fired",
        range: "close",
        accuracy: 75,
        recoil: 2,
        rarity: "Legendary",
        named: true,
        unique: true,
        faction: "aegis",
        slots: [],
        load: 2,
        art: null,
        authority: [],
        upgrades: [],
      },
      {
        id: "balance",
        name: "The Balance",
        family: "maul",
        caliber: null,
        capacity: 0,
        damage: 10,
        penetration: 0,
        owner: "valdris",
        region: "slagtown",
        feed: "none",
        operation: "manually fired",
        range: "close",
        accuracy: 75,
        recoil: 2,
        rarity: "Legendary",
        named: true,
        unique: true,
        faction: null,
        slots: [],
        load: 2,
        art: null,
        authority: ["furnace-control"],
        upgrades: [
          {
            name: "Thermal Maul",
            requirement: "valdris",
            effect: "Industrial plate-breaking strike",
            visual: "heated head",
          },
          {
            name: "Coolant Jacket",
            requirement: "coolant-parts",
            effect: "Longer use before heat lockout",
            visual: "jacket",
          },
          {
            name: "Helios Head",
            requirement: "helios",
            effect: "Controlled superheat",
            visual: "thermal matrix",
          },
          {
            name: "Tithe Interface",
            requirement: "tithe-keys",
            effect: "Physical furnace control interface",
            visual: "token socket",
          },
          {
            name: "Debt Comes Due",
            requirement: "slag-outcome",
            effect: "Possession determines industrial authority",
            visual: "control handle",
          },
        ],
      },
      {
        id: "arc-spanner",
        name: "Arc Spanner",
        family: "maul",
        caliber: null,
        capacity: 0,
        damage: 10,
        penetration: 0,
        owner: "mercer",
        region: "veyra",
        feed: "none",
        operation: "manually fired",
        range: "close",
        accuracy: 75,
        recoil: 2,
        rarity: "Legendary",
        named: true,
        unique: true,
        faction: null,
        slots: [],
        load: 2,
        art: null,
        authority: [],
        upgrades: [],
      },
    ] as WeaponDefinition[]
  ).map((w) => [w.id, w]),
);
export const ITEMS: Record<string, ItemDefinition> = Object.fromEntries(
  (
    [
      {
        id: "bay-roll",
        name: "Bay 13 Roll",
        category: "utility",
        owner: "travis",
        load: 1,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "grey-guitar",
        name: "Grey Guitar",
        category: "keepsake",
        owner: "travis",
        load: 1,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "continuity-glass",
        name: "Continuity Glass",
        category: "utility",
        owner: "kane",
        load: 1,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "glassbook",
        name: "Glassbook",
        category: "utility",
        owner: "soren",
        load: 1,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "mnemonic-needles",
        name: "Mnemonic Needles",
        category: "utility",
        owner: "soren",
        load: 1,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "ward-drones",
        name: "Ward Drones",
        category: "utility",
        owner: "soren",
        load: 1,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "genesis-rig",
        name: "Genesis Rig",
        category: "rig",
        owner: "quell",
        load: 2,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "seedcaster",
        name: "Seedcaster",
        category: "utility",
        owner: "quell",
        load: 1,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "green-vault",
        name: "Green Vault",
        category: "utility",
        owner: "quell",
        load: 1,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "bridge-harness",
        name: "Bridge Harness",
        category: "rig",
        owner: "mercer",
        load: 2,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "rift-lens",
        name: "Rift Lens",
        category: "utility",
        owner: "mercer",
        load: 1,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "archive-spike",
        name: "Archive Spike",
        category: "utility",
        owner: "reeve",
        load: 1,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "whisperlace",
        name: "Whisperlace",
        category: "armor",
        owner: "lyra",
        load: 2,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "moth",
        name: "MOTH Microdrone",
        category: "utility",
        owner: "lyra",
        load: 1,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "edict",
        name: "Edict Projector",
        category: "utility",
        owner: "vera",
        load: 1,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "ledger-drone",
        name: "Ledger Drone",
        category: "utility",
        owner: "vera",
        load: 1,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "breach-mantle",
        name: "Breach Mantle",
        category: "armor",
        owner: "drake",
        load: 2,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "door-tax",
        name: "Door Tax",
        category: "utility",
        owner: "drake",
        load: 1,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "grav-hooks",
        name: "Grav Hooks",
        category: "utility",
        owner: "orion",
        load: 1,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "null-skin",
        name: "Null Skin",
        category: "armor",
        owner: "orion",
        load: 2,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "pack-whistle",
        name: "Pack Whistle",
        category: "utility",
        owner: "gravenor",
        load: 1,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "route-cloak",
        name: "Route Cloak",
        category: "armor",
        owner: "gravenor",
        load: 2,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "chancellor-rig",
        name: "Chancellor Rig",
        category: "rig",
        owner: "valdris",
        load: 2,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "scar-harness",
        name: "Scar Harness",
        category: "rig",
        owner: "thessaly",
        load: 2,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "seismic-tags",
        name: "Seismic Tags",
        category: "utility",
        owner: "thessaly",
        load: 1,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "citadel-shield",
        name: "Citadel Shield",
        category: "utility",
        owner: "warden",
        load: 1,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "warden-frame",
        name: "Warden Frame",
        category: "rig",
        owner: "warden",
        load: 2,
        unique: true,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "deadman-key",
        name: "Deadman Key",
        category: "authority",
        owner: "travis",
        load: 0,
        unique: true,
        authority: ["t0880-maintenance"],
        protection: 0,
        art: null,
      },
      {
        id: "black-key",
        name: "Black Key",
        category: "authority",
        owner: "kane",
        load: 0,
        unique: true,
        authority: ["vesper-emergency"],
        protection: 0,
        art: null,
      },
      {
        id: "grey-credentials",
        name: "Grey Credentials",
        category: "authority",
        owner: "reeve",
        load: 0,
        unique: true,
        authority: ["recovery-warrant"],
        protection: 0,
        art: null,
      },
      {
        id: "bottom-key",
        name: "Bottom Key",
        category: "authority",
        owner: "sink",
        load: 0,
        unique: true,
        authority: ["bounded-flood-control"],
        protection: 0,
        art: null,
      },
      {
        id: "violet-crown",
        name: "Violet Crown",
        category: "authority",
        owner: "orion",
        load: 0,
        unique: true,
        authority: ["aegis-command"],
        protection: 0,
        art: null,
      },
      {
        id: "tithe-keys",
        name: "Tithe Keys",
        category: "authority",
        owner: "valdris",
        load: 0,
        unique: true,
        authority: ["furnace-control"],
        protection: 0,
        art: null,
      },
      {
        id: "aegis-blackbox",
        name: "AEGIS blackbox",
        category: "authority",
        owner: null,
        load: 0,
        unique: false,
        authority: ["decision-record"],
        protection: 0,
        art: null,
      },
      {
        id: "ironbound-carrier",
        name: "Ironbound Plate Carrier",
        category: "armor",
        owner: null,
        load: 2,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "bulwark",
        name: "Warden-Pattern Bulwark",
        category: "armor",
        owner: null,
        load: 2,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "medic-rig",
        name: "Field Medic Rig",
        category: "rig",
        owner: null,
        load: 2,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "kilnrunner",
        name: "Kilnrunner Kit",
        category: "armor",
        owner: null,
        load: 2,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "dredger",
        name: "Dredger Shell",
        category: "armor",
        owner: null,
        load: 2,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "lantern-coat",
        name: "Lantern Coat",
        category: "armor",
        owner: null,
        load: 2,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "aegis-frame",
        name: "AEGIS Frame",
        category: "rig",
        owner: null,
        load: 2,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "trauma-roll",
        name: "Trauma Roll",
        category: "medical",
        owner: null,
        load: 1,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "field-gel",
        name: "Field Gel",
        category: "medical",
        owner: null,
        load: 1,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "cinderlung",
        name: "Cinderlung Serum",
        category: "medical",
        owner: null,
        load: 1,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "respirator",
        name: "Ash Filter Respirator",
        category: "utility",
        owner: null,
        load: 1,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "rivetguard",
        name: "Rivetguard Vest",
        category: "armor",
        owner: null,
        load: 2,
        unique: false,
        authority: [],
        protection: 2,
        art: "./art/items/rivetguard.jpg",
      },
      {
        id: "radio",
        name: "Crank Radio",
        category: "utility",
        owner: null,
        load: 1,
        unique: false,
        authority: [],
        protection: 0,
        art: "./art/items/crank-radio.jpg",
      },
      {
        id: "grease",
        name: "Black Rail Grease",
        category: "utility",
        owner: null,
        load: 1,
        unique: false,
        authority: [],
        protection: 0,
        art: "./art/items/grease-tin.jpg",
      },
      {
        id: "servo-ring",
        name: "AEGIS Servo Ring",
        category: "material",
        owner: null,
        load: 1,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "helios-regulator",
        name: "Helios Thermal Regulator",
        category: "material",
        owner: null,
        load: 1,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "cognition-lattice",
        name: "Blackglass Cognition Lattice",
        category: "material",
        owner: null,
        load: 1,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "spring-steel",
        name: "Spring steel",
        category: "material",
        owner: null,
        load: 1,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "optical-glass",
        name: "Optical glass",
        category: "material",
        owner: null,
        load: 1,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "refractory-alloy",
        name: "Refractory alloy",
        category: "material",
        owner: null,
        load: 1,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "cold-seal",
        name: "Cold seal compound",
        category: "material",
        owner: null,
        load: 1,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "marine-brass",
        name: "Marine brass / sealant",
        category: "material",
        owner: null,
        load: 1,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "capacitors",
        name: "Recovered capacitors",
        category: "material",
        owner: null,
        load: 1,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
      {
        id: "aegis-material",
        name: "AEGIS ceramic / servo alloy",
        category: "material",
        owner: null,
        load: 1,
        unique: false,
        authority: [],
        protection: 0,
        art: null,
      },
    ] as ItemDefinition[]
  ).map((i) => [i.id, i]),
);

ITEMS["recovery-warrant"] = {
  id: "recovery-warrant",
  name: "Vesper recovery warrant",
  category: "authority",
  owner: null,
  load: 0,
  unique: true,
  authority: ["rail-records"],
  protection: 0,
  art: null,
};
